# 每天进行 Telegram Bot 签到的时间范围, 等同于命令行 "-c" 参数.
time = "<0:00AM,1:00AM>"

# 将关键信息发送到第一个 Telegram 账号, 设为 N 以发送到第 N 个.
notifier = true

# 每个 Telegram Bot 签到的最大尝试时间 (秒).
timeout = 240

# 每个 Telegram Bot 签到的最大尝试次数.
retries = 3

# 最大可同时进行的 Telegram Bot 签到.
concurrent = 1

# 计划任务时, 各站点之间签到的随机时间差异 (分钟), 所有站点签到将在该时间范围内完成.
random = 15

# 代理设置, Emby 和 Telegram 均将通过此代理连接, 服务器位于国内时请配置代理并取消注释.
# 详见: https://emby-keeper.github.io/guide/配置文件#proxy-子项
[proxy]
hostname = "127.0.0.1"
port = 7890
scheme = "http" # 可选: http / socks5

[service]
checkiner = ["zm", "sfcju", "lyrebird", "micu", "tdck"]

[[telegram]]
phone = "+8613255802980"
checkin = true
send = false
monitor = false
